let exercise = {
  shoulder: [
    "arnold press",
    "press behind the neck",
    "dumbbel press",
    "milatry press",
    "clean and press",
    "machine press",
    "push press",
    "standing lateral raises",
    "one arm side cabe lateral",
    "seated one arm cross cabel lateral",
    ,
    "reverse over head dumbbel lateral",
    "front dumbbel raises",
    "seated bent-over dumbbel lateral",
    "standing bent-over dumbbel lateral",
    "bent-over cable lateral",
    "lying side lateral",
  ],
  trapeziues: [
    "upright rows",
    "heavy upright rows",
    "dumbbel shrugs",
    "barbel shrugs",
  ],
  chest: [
    "barbel flat bench press",
    "dubbel flat bench press",
    "incline dumbbel press",
    "decline dumbbel press",
    "parallel dips",
    "machine press",
    "dumbbel fly",
    "incline dumbbel fly",
    "standing cable fly",
    "bent-forward cable cross over",
    "flat bench cable cross over",
    "machine fly",
    "staight-arm pull-over",
    "rope pull-over",
    "one arm cable pull",
  ],
  back: [
    "wide grip chin ups behind the neck",
    "wide grip chin ups",
    "close grip chin ups",
    "pull down",
    "late machine pull down",
    "late machine pull down behind the neck",
    "bent-over barbel rows",
    "bent-over dumbbel rows",
    "t-bar rows",
    "machine pullover",
    "one-arm dumbbel rows",
    "one-arm cable rows",
    "seated cable rows",
    "bent arm pull over with barbel",
    "dead-lift",
    "hyper extension",
    "goodmorning",
  ],
  biceps: [
    "standing barbel curls",
    "cheat curls",
    "precher curls",
    "3 part curls",
    "incline dumbble curls",
    "seated dumbbel curls",
    "hammer curls",
    "alternative dumbbel curls",
    "cunsontration  curls",
    "lying dumbbel curls",
    "two-hand cable curls",
    "cable curls with preacher",
    "reverse curls",
    "reverse preacher curls",
  ],
  triceps: [
    "late machine press down",
    "arm blaster press down",
    "one-arm cable reverse press down",
    "seated triceps press",
    "standing triceps press",
    "lying triceps extension",
    "close grip extension",
    "lying dumbbel extension",
    "lying cross press triceps extension",
    "dumbbel kickback",
    "one-arm triceps extension",
    "dips",
    "dips behind the neck",
    "fixed bar triceps extension",
  ],
  arm: [
    "barbel wrist curls",
    "dumbbel one-arm wrist curls",
    "behind the back wrist curls",
    "reverse wrist curls with barbel",
    "reverse  barbel wrist curls with preacher bench",
    "reverse wrist curls with dumbbel",
    "reverse barbel curls",
    "reverse preacher bench barbel curls",
    ,
    "reverse curls one a machine",
    "one-arm cable reverse curls",
  ],
  thighs: [
    "squats",
    "half squats",
    "machine squats",
    "front squats",
    "front half squats",
    "leg press",
    "hack squats",
    "lungs",
    "leg extension",
    "leg curls",
    "standing leg curls",
    "straight leg deadlift",
  ],
  calf: [
    "standing calf raises",
    "calf raises one leg pres",
    "seated calf raises",
    "donkey calf raises",
    "one-leg calf raises",
    "reverse calf raises",
  ],
  abs: [
    "incline board sit-ups",
    "twisting sit-ups",
    "sit-ups on floor",
    "knees-in-air sit-ups",
    "twisting knee-in-air sit-ups",
    "romen chair sit-ups",
    "sit-ups",
    "incline board leg raises",
    "bent-knee incline board leg raises",
    "flat bench leg raises",
    "bent-knee flat bench leg raises",
    "hanging leg raises",
    "verticle bench leg raises",
    "bent-knee verticle bench leg raises",
    "verticle bench alternate leg raises",
    "seated leg tukd",
    "leg tukd one floor",
    "alternate leg raises",
    "alternate twisting knee raises",
    "cruches",
    "toe-touch crunch",
    "alternate machine cruch",
    "standing bent over twist",
    "side leg raises",
    "bent-knee leg raises",
    "front kick",
    "bench kickback",
    "rear leg sissor",
  ],
};
